<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::post('vCj1lBA/5D7xhyuEFuIAwabFNqgR',[
    'uses'=>'CoursesController@getCourse'
]);
Route::get('welcome/blogs',[
    'uses'=>'IndexController@WelcomeBlog'
]);
Route::get('/welcome/hacks',[
    'uses'=>'IndexController@WelcomeHack'
]);
Route::get('getCracksMenu',[
    'uses'=>'CracksController@Menus'
]);
Route::get('/getCracksMenu',[
    'uses'=>'CracksController@getCracksMenu'
]);
Route::get('/ZM1LDQPNwhQ1wRDEpn5oe',[
    'uses'=>'CoursesController@TopRated'
]);
Route::get('/3fb3I6D1Nfyu7t3jSV3RB74',[
    'uses'=>'CoursesController@All'
]);
Route::get('getBlogCategories',[
    'uses'=>'BlogsController@Categories'
]);
Route::get('/getBlogs',[
    'uses'=>'BlogsController@Blogs'
]);
Route::get('/GetSingleBlog/{slug}',[
    'uses'=>'BlogsController@SingleBlog'
]);
Route::get('/getOne/{category}',[
    'uses'=>'BlogsController@getSingle'
]);
Route::get('/getTechCategories',[
    'uses'=>'TechsController@THacksCategories'
]);
Route::get('/getAllHacks',[
    'uses'=>'TechsController@getAllHacks'
]);
Route::get('/TechHack/{slug}',[
    'uses'=>'TechsController@SingleHack'
]);
Route::get('getOneHack/{category}',[
    'uses'=>'TechsController@getOneHack'
]);
Route::get('Course/{slug}',[
    'uses'=>'CoursesController@SingleCourse'
]);
Route::get('getCracks',[
    'uses'=>'CracksController@getAll'
]);
Route::get('/sppCat/{CatName}',[
    'uses'=>'CracksController@Specific'
]);
Route::get('Crack/{slug}',[
    'uses'=>'CracksController@SingleCrack'
]);
Route::get('/Courses/Edit/{id}',[
    'uses'=>'CoursesController@edit'
]);
Route::get('PY7Ux7bqLcOYSET',[
    'uses'=>'CoursesController@GetLatest'
]);
Route::get('NtEeRAZWyEkd6QBNQNphgf7',[
    'uses'=>'MenusController@Menus'
]);
Route::get('/QNphgf7gGV6qEoh7g',[
    'uses'=>'CoursesController@TopRatedMenu'
]);
Route::get('/FWfROKZ6S84tBlJxm9iX0tLfoz',[
    'uses'=>'CoursesController@High'
]);
Route::get('/bz77CIjJaY2B8Soi/{id}',[
    'uses'=>'CategoriesController@GetCourse'
]);
Route::get('/Top/Rated',[
    'uses'=>'CoursesController@Top'
]);
Route::get('Courses',[
    'uses'=>'CoursesController@index',
    'as'=>'courses'
]);
Route::get('TechHacks',[
'uses'=>'TechsController@TechHacks',
'as'=>'techs'
]);
Route::get('/Cracked/Software',[
    'uses'=>'CracksController@Cracks',
    'as'=>'cracks'
]);
Route::get('Blog',[
    'uses'=>'BlogsController@Blog',
    'as'=>'blog'
]);
Route::get('AboutUs',[
    'uses'=>'BlogsController@AboutUs',
    'as'=>'AboutUs'
]);
Route::get('Contact',[
    'uses'=>'BlogsController@ContactUs',
    'as'=>'contact'
]);
Route::get('/','IndexController@home');
Route::get('/cat', function () {
    return view('Single');
});
Route::get('/rDAveiHCeuWm098JJNYPjB','IndexController@index');
Auth::routes();
// Route::post('/Login/check','Auth\LoginController@index')->name('login');

// Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/Menus',[
    'uses'=>'MenusController@index',
    'as'=>'menus'
]);
Route::post('/Menus/Add',[
    'uses'=>'MenusController@store',
    'as'=>'menu.add'
]);
Route::get('/Blog/Menus',[
    'uses'=>'BlogsController@Menus',
    'as'=>'bmenus'
]);
Route::post('blog/Categories',[
    'uses'=>'BlogsController@SaveCat'
]);
Route::get('/blog/Categories',[
    'uses'=>'BlogsController@BlogCat'
]);
Route::post('delete/menu',[
    'uses'=>'BlogsController@dcat'
]);
Route::get('/Menus/Add/{id}',[
    'uses'=>'MenusController@destroy',
    'as'=>'menu.delete'
]);
Route::get('/Course/View/{slug}',[
    'uses'=>'CoursesController@specific',
    'as'=>'Course'
]);

Route::get('/Courses/View/{menu}',[
    'uses'=>'CoursesController@single',
    'as'=>'View'
]);

Route::get('/Payment',[
    'uses'=>'PaymentController@index'
]);
Route::get('/Payment/Callback',[
    'uses'=>'PaymentController@callback'
]);
Route::get('/Payment/Validation',[
    'uses'=>'PaymentController@validation'
]);
Route::post('/Course/Store',[
    'uses'=>'CoursesController@store',
    'as'=>'course.store'
]);
Route::get('/FetchHacks',[
    'uses'=>'TechsController@getAll'
]);
Route::get('Hack/Show/{id}',[
    'uses'=>'TechsController@show'
]);
Route::get('Delete/Hack/{id}',[
    'uses'=>'TechsController@destroy'
]);
Route::post('/Course/Update/id',[
    'uses'=>'CoursesController@Update'
]);
Route::get('/Courses/Manage',[
    'uses'=>'CoursesController@Manage',
    'as'=>'courses.manage'
]);
Route::get('/Course/EDAqAP7B/0W0ujLdMFdO6M9U3yLrrpI9urhugjfI',[
    'uses'=>'CoursesController@index',
    'as'=>'courses'
]);
Route::get('/Course/View/{id}',[
    'uses'=>'CoursesController@show',
    'as'=>'course.view'
]);
Route::group(['middleware' => ['auth']], function () {
    Route::get('/Course/EDgXSAqAP7BgLHT/0W0ujLdMFdO6M9U3y9urhugjfIagXS/{id}',[
        'uses'=>'CoursesController@destroy',
        'as'=>'course.delete'
    ]);
    Route::get('/CountCourses',[
        'uses'=>'IndexController@CourseCount'
    ]);
    Route::get('/CountTech',[
        'uses'=>'IndexController@TechCount'
    ]);
    Route::get('/CountCrack',[
        'uses'=>'IndexController@CracksCount'
    ]);
    Route::get('/CountBlog',[
        'uses'=>'IndexController@BlogCount'
    ]);
    Route::get('/CrackMenuCount',[
        'uses'=>'IndexController@CracksMenuCount'
    ]);
    Route::get('/MessagesCount',[
        'uses'=>'IndexController@MessageCount'
    ]);
    Route::get('/TechMenuCount',[
        'uses'=>'IndexController@TechCount'
    ]);
    Route::resource('Techs','TechsController');
    Route::get('/Course/EDgXSAqAP7BgLHT/0W0ujLdMM9U3yLrrpI9urhugjfIag/{id}',[
        'uses'=>'CoursesController@edit',
        'as'=>'course.edit'
    ]);
    Route::post('vqgjiDdKDjvKgp49o',[
        'uses'=>'TechsController@Categories'
    ]);
    Route::get('/cJGqyURLYO9HbcO3F0VH1',[
        'uses'=>'TechsController@getCategories'
    ]);
    Route::post('Category/JKv6i9IqrBhh2hZgObRAOs6HPAzZQZW2Uv',[
        'uses'=>'TechsController@deleteCat'
    ]);
    Route::post('/Course/ESAqAP7BgLHT/0W0ujLdMFdO6M9U3yLrrpI9urhugjfIag/{id}',[
        'uses'=>'CoursesController@update',
        'as'=>'course.update'
    ]);
    Route::get('/Course/EDgXSAqAP7BgLHT/0W0ujLdMFdO6M9U3yLrrpI9urhugjfIagXS',[
        'uses'=>'CoursesController@create',
        'as'=>'course.add'
    ]);
    Route::post('Course/JPUFR37qMEr64CHDO0UiQQAIiniSy/{id}',[
        'uses'=>'CoursesController@destroy',
        'as'=>'course.delete'
    ]);
    Route::get('Course/View/4qnPjr6Ycg66gOfqyUXQagQSSkp3/{id}',[
        'uses'=>'CoursesController@show'
    ]);
    // Route::get('/create/blog',[
    //     'uses'=>'BlogsController@create',
    //     'as'=>'blog.create'
    // ]);
    Route::resource('blog','BlogsController');
    Route::resource('cracks','CracksController');
    Route::post('/CracksMenu',[
        'uses'=>'CracksController@CracksMenu'
    ]);
    Route::post('/Blog/Store',[
        'uses'=>'BlogsController@store',
        'as'=>'blog.store'
    ]);
    Route::get('/FetchBlogs',[
        'uses'=>'BlogsController@Fetch',
    ]);
    Route::get('/Blog/Show/{id}',[
        'uses'=>'BlogsController@show'
    ]);
    Route::get('/Delete/article/{id}',[
        'uses'=>'BlogsController@destroy'
    ]);
    Route::post('/Delete/cmenu',[
        'uses'=>'CracksController@cDelete'
    ]);
    Route::get('/cracks/All/get',[
        'uses'=>'CracksController@All',
        'as'=>'cracks.manage'
    ]);
    Route::get('/CracksAll',[
        'uses'=>'CracksController@Api'
    ]);
    Route::get('/cracks/edit/{id}',[
        'uses'=>'CracksController@edit',

    ]);
    Route::get('/Single/Crack/{id}',[
        'uses'=>'CracksController@Single'
    ]);
    Route::get('/Delete/Crack/{id}',[
        'uses'=>'CracksController@destroy'
    ]);
    Route::post('/Messages/Controller',[
        'uses'=>'IndexController@store'
    ]);
    Route::get('/Messages',[
        'uses'=>'IndexController@Messages',
        'as'=>'messages'
    ]);
    Route::get('/Get/AllMessages',[
        'uses'=>'IndexController@Api',

    ]);
});
